### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by ipcjs** [ipcjs/pakku.js#1]
试图支持过滤WebSocket下发的弹幕。。。

1. [ ] hook Array.push => 1%
3. [ ] 处理弹幕的方法输入输出改成array
2. [ ] hook WebSocket.onMessage
4. [ ] 在接收到新弹幕时重新计算，在触发Array.push方法时，替换所有的弹幕
